
(()=>{
'use strict';
const GA={tools:[],activeTool:null,personal:{enabled:true,style:'gentle',beliefVariants:true},currentItem:null,learn:null,collections:[],journalRows:[]};
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],val=id=>q('#'+id)?.value?.trim?.()||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const txt=(id,v)=>{const e=q('#'+id);if(e)e.textContent=v??''};const toast=m=>showSync(m);
const PH=[{key:'stabilize',name:'Stabilize',start:1,end:30,desc:'Safety, steadiness, support, and the next manageable choice.'},{key:'build',name:'Build',start:31,end:60,desc:'Routines, coping, support, and recovery protection.'},{key:'understand',name:'Understand',start:61,end:90,desc:'Patterns, triggers, thoughts, emotions, and needs.'},{key:'rebuild',name:'Rebuild',start:91,end:120,desc:'Daily life, responsibilities, boundaries, relationships, and self-trust.'},{key:'strengthen',name:'Strengthen',start:121,end:150,desc:'Warning signs, relapse prevention, boundaries, and recovery under pressure.'},{key:'grow',name:'Grow',start:151,end:183,desc:'Identity, values, purpose, connection, and a fuller recovery life.'},{key:'maintenance',name:'Maintenance',start:184,end:365,desc:'Protect what works and adapt recovery as life changes.'},{key:'year_2',name:'Year Two',start:366,end:730,desc:'Build durable, self-directed recovery and long-range goals.'},{key:'long_term',name:'Long-Term Recovery',start:731,end:999999,desc:'Lighter weekly guidance, annual review, and support when life changes.'}];
const phaseFor=d=>PH.find(p=>d>=p.start&&d<=p.end)||PH[PH.length-1];
const pct=d=>{const p=phaseFor(d);return p.key==='long_term'?100:Math.max(0,Math.min(100,((d-p.start+1)/(p.end-p.start+1))*100))};
function anchor(d){if(d<=183)return{day:d,mode:'daily'};if(d<=365)return{day:184+Math.floor((d-184)/7)*7,mode:'weekly'};if(d<=730)return{day:366+Math.floor((d-366)/7)*7,mode:'weekly'};return{longIndex:(Math.floor((d-731)/7)%12)+1,mode:'weekly'}}
function fallback(d){let list=d<=30?phase1Curriculum:d<=60?phase2Curriculum:d<=90?phase3Curriculum:d<=120?phase4Curriculum:d<=150?phase5Curriculum:d<=183?phase6Curriculum:d<=365?maintenanceCurriculum:year2Curriculum;const a=anchor(d),r=(list||[]).find(x=>x.d===a.day)||(list||[])[0];return{day_number:r?.d||d,phase_key:phaseFor(d).key,title:r?.t||'Recovery Check-In',summary:r?.lead||'Notice what matters today.',prompt:r?.focus||'What deserves your attention?',choices:r?.choices||[],actions:r?.actions||[],reflection_prompt:'What do you want to remember from this?',cadence:a.mode}}
async function contentFor(d=daysInRecovery()){const a=anchor(d);try{let r=a.longIndex?await sb.from('journey_content').select('*').eq('phase_key','long_term').eq('cadence_index',a.longIndex).eq('published',true).maybeSingle():await sb.from('journey_content').select('*').eq('day_number',a.day).eq('published',true).maybeSingle();if(!r.error&&r.data)return r.data}catch(e){}return fallback(d)}
function beliefOption(){if(!GA.personal.beliefVariants)return null;const b=String(data.belief||'').toLowerCase(),faith=String(data.faith||'').toLowerCase(),den=String(data.denomination||'').toLowerCase();if(b.includes('secular'))return null;if(b.includes('faith')){if(faith==='christian'&&den==='baptist')return 'Optional: prayer, Scripture reflection, or contact with a trusted Baptist church/recovery support.';if(faith==='christian')return 'Optional: prayer, Scripture reflection, or connection with a trusted Christian support person.';return 'Optional: include a prayer or faith practice that fits your tradition.'}if(b.includes('spiritual')||b.includes('mixed'))return 'Optional: include meditation, prayer, nature, or another spiritual practice if it helps.';return null}
async function renderJourney(){const d=daysInRecovery(),p=phaseFor(d),item=await contentFor(d),a=anchor(d),next=PH[PH.indexOf(p)+1];txt('journeyDayNumber',d);txt('journeyPhaseKicker',`${a.mode.toUpperCase()} GUIDANCE • CURRENT PHASE`);txt('journeyPhaseTitle',p.name);txt('journeyPhaseDescription',p.desc);if(q('#journeyPhaseMeter'))q('#journeyPhaseMeter').style.width=pct(d)+'%';txt('journeyPhaseProgress',p.key==='long_term'?`Recovery Day ${d} • weekly long-term guidance`:`${Math.round(pct(d))}% through ${p.name}`);txt('journeyNextTransition',next?next.name:'Annual Review');txt('journeyNextTransitionText',next?`${Math.max(0,next.start-d)} days until the next phase`:'Long-term recovery continues without an end date');txt('journeyTodayTitle',item.title);txt('journeyTodaySummary',item.summary);const box=q('#journeyRoadmap');if(box)box.innerHTML=PH.map((x,i)=>{const st=x.key===p.key?'current':d>x.end?'past':'future',label=x.key==='long_term'?'YEAR 3+':x.key==='year_2'?'DAYS 366–730':x.key==='maintenance'?'DAYS 184–365':`DAYS ${x.start}–${x.end}`;return`<article class="approved-phase-step ${st}"><span>${i+1}</span><div><small>${label}</small><h3>${x.name}</h3><p>${st==='current'?'Current phase':st==='past'?'Available to review':'Opens later'}</p></div></article>`}).join('')}
async function renderGuided(){const d=daysInRecovery(),p=phaseFor(d),item=await contentFor(d),a=anchor(d);GA.currentItem=item;txt('guidedDayPhase',`${p.name.toUpperCase()} • ${a.mode.toUpperCase()} GUIDANCE`);txt('guidedDayTitle',item.title);txt('guidedDayLead',item.summary);txt('guidedDayLabel',`DAY ${d}`);txt('guidedPhaseLabel',p.name);if(q('#guidedPhaseBar'))q('#guidedPhaseBar').style.width=pct(d)+'%';txt('guidedPromptTitle',item.prompt);txt('guidedPromptText','Choose anything that fits. You can skip every choice.');txt('guidedReflectionPrompt',item.reflection_prompt||'A few words is enough.');q('#guidedChoiceGrid').innerHTML=(item.choices||[]).map(x=>`<button type="button" class="day2-choice">${esc(x)}</button>`).join('');let acts=[...(item.actions||[])],belief=beliefOption();if(belief)acts.push(belief);q('#guidedActionChoices').innerHTML=acts.map(x=>`<button type="button" class="day2-choice">${esc(x)}</button>`).join('');qa('#guidedChoiceGrid .day2-choice').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));qa('#guidedActionChoices .day2-choice').forEach(b=>b.onclick=()=>{qa('#guidedActionChoices .day2-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});q('#groupABeliefNote')?.remove();if(belief){const n=document.createElement('div');n.id='groupABeliefNote';n.className='groupa-belief-note';n.textContent='Belief-aligned options are optional and never replace clinical or safety guidance.';q('.approved-next-step-card')?.appendChild(n)}await loadGuided()}
async function loadGuided(){if(!currentUser||!GA.currentItem)return;const key=`journey_core_${GA.currentItem.day_number||('long_'+anchor(daysInRecovery()).longIndex)}`;try{const{data:r}=await sb.from('guided_responses').select('*').eq('user_id',currentUser.id).eq('response_date',todayKey()).eq('prompt_key',key).maybeSingle();if(!r)return;const choices=Array.isArray(r.selected_choices)?r.selected_choices:[];qa('#guidedChoiceGrid .day2-choice').forEach(b=>b.classList.toggle('selected',choices.includes(b.textContent.trim())));if(q('#guidedReflectionText'))q('#guidedReflectionText').value=r.optional_reflection||'';const act=r.metadata?.selected_action;qa('#guidedActionChoices .day2-choice').forEach(b=>b.classList.toggle('selected',b.textContent.trim()===act))}catch(e){}}
async function saveGuided(){if(!currentUser||!GA.currentItem)return alert('Please sign in first.');const item=GA.currentItem,key=`journey_core_${item.day_number||('long_'+anchor(daysInRecovery()).longIndex)}`,selected=qa('#guidedChoiceGrid .day2-choice.selected').map(x=>x.textContent.trim()),action=q('#guidedActionChoices .day2-choice.selected')?.textContent.trim()||null;const payload={user_id:currentUser.id,response_date:todayKey(),recovery_day:daysInRecovery(),phase_key:phaseFor(daysInRecovery()).key,curriculum_day:item.day_number||daysInRecovery(),content_slug:`group-a-${key}`,prompt_key:key,prompt_version:1,prompt_text:item.prompt,selected_choices:selected,optional_reflection:val('guidedReflectionText')||null,allow_milestone_review:true,allow_recovery_story:false,metadata:{selected_action:action,title:item.title,cadence:anchor(daysInRecovery()).mode}};const{error}=await sb.from('guided_responses').upsert(payload,{onConflict:'user_id,response_date,prompt_key'});if(error)return alert(error.message);if(action)await sb.from('recovery_actions').insert({user_id:currentUser.id,action_date:todayKey(),action_type:'recovery_action',content:action,completed:true});toast("Today's guidance saved.");renderHistory();personalize()}
async function renderHistory(){const box=q('#journeyHistoryList');if(!box||!currentUser)return;try{const{data:r}=await sb.from('guided_responses').select('*').eq('user_id',currentUser.id).like('prompt_key','journey_core_%').order('response_date',{ascending:false}).limit(50);box.innerHTML=(r||[]).length?r.map(x=>`<article class="groupa-history-card"><small>${x.response_date}${x.recovery_day?` • Day ${x.recovery_day}`:''} • ${esc((x.phase_key||'').replace('_',' '))}</small><h3>${esc(x.metadata?.title||x.prompt_text)}</h3><p>${esc((x.selected_choices||[]).join(' • ')||'No choices selected')}${x.optional_reflection?`<br><em>${esc(x.optional_reflection)}</em>`:''}</p></article>`).join(''):'<div class="approved-resource-empty"><b>No saved guided days yet.</b></div>'}catch(e){box.innerHTML='<div class="approved-resource-empty">Run the Group A SQL to activate guided history.</div>'}}

const FALLBACK=[
{slug:'craving-reset',title:'Craving Reset',category:'cravings',summary:'Create distance from an urge and protect the next few minutes.',steps:['Name the urge without arguing with it.','Move away from alcohol, drugs, or a high-risk setting if you can.','Contact a safe support person before the urge becomes stronger.','Use water, food, movement, grounding, or a meeting to create time.','Reassess after the urge has had time to change.'],recommended_for:['craving','urge','substance'],symbol:'◉'},
{slug:'urge-surfing',title:'Urge Surfing',category:'cravings',summary:'Notice an urge as a changing wave instead of a command.',steps:['Notice where the urge shows up in your body.','Describe the sensation without fighting it.','Watch for changes in intensity.','Keep yourself away from access while the urge rises and falls.','Use support if the urge is becoming unsafe.'],recommended_for:['craving','urge'],symbol:'≈'},
{slug:'grounding-54321',title:'5-4-3-2-1 Grounding',category:'calming',summary:'Bring attention back to the present when thoughts or anxiety are racing.',steps:['Name 5 things you can see.','Name 4 things you can physically feel.','Name 3 things you can hear.','Name 2 things you can smell.','Name 1 thing you can taste or one breath you can notice.'],recommended_for:['anxious','overwhelmed','panic'],symbol:'◎'},
{slug:'paced-breathing',title:'Paced Breathing',category:'calming',summary:'Use a slower exhale to help your body settle.',steps:['Sit or stand somewhere safe.','Breathe in gently.','Let the exhale be a little longer than the inhale.','Repeat without forcing a very deep breath.','Stop if breathing exercises make you feel worse and choose another grounding tool.'],recommended_for:['stress','angry','overwhelmed'],symbol:'≈'},
{slug:'halt-check',title:'HALT Check',category:'planning',summary:'Check whether hunger, anger, loneliness, or tiredness is making recovery harder.',steps:['Ask: am I hungry?','Ask: am I angry or activated?','Ask: am I lonely or disconnected?','Ask: am I tired?','Meet the most basic need first, then reassess.'],recommended_for:['hungry','angry','lonely','tired'],symbol:'H'},
{slug:'trigger-review',title:'Trigger Review',category:'triggers',summary:'Study what happened before an urge without blaming yourself.',steps:['What happened just before the urge?','Who was there?','What were you feeling or thinking?','What warning sign showed up first?','What could create more safety next time?'],recommended_for:['trigger','people','places','conflict'],symbol:'↻'},
{slug:'exit-plan',title:'Exit a High-Risk Situation',category:'cravings',summary:'Make leaving easier when substances or risky people are nearby.',steps:['Decide that leaving is allowed even if it feels awkward.','Move toward a safer location.','Contact someone who supports your recovery.','Arrange safe transportation if needed.','Once safe, decide what support you need next.'],recommended_for:['around substances','risky place'],symbol:'↗'},
{slug:'anger-pause',title:'Anger Pause',category:'calming',summary:'Create space before saying or doing something that could make things harder.',steps:['Do not send the message or continue the argument yet.','Move away if it is safe.','Notice what your body is doing.','Use grounding, walking, or another calming tool.','Return only when you can choose your next action.'],recommended_for:['angry','conflict'],symbol:'!'},
{slug:'connection-step',title:'Move Toward Connection',category:'connection',summary:'Use a small connection step before loneliness becomes isolation.',steps:['Name one safe person or place.','Choose a low-pressure contact: text, call, meeting, or shared activity.','Say something simple such as “I could use some company.”','If one person is unavailable, try another support.','Do not treat one unavailable person as a reason to isolate.'],recommended_for:['lonely','alone','isolating'],symbol:'♡'},
{slug:'sleep-reset',title:'Sleep Reset',category:'sleep',summary:'Protect recovery by making tonight a little easier on your body and mind.',steps:['Choose a realistic bedtime window.','Reduce stimulating screens or conflict close to bedtime.','Limit late caffeine if it affects you.','Prepare the room for sleep.','Discuss persistent or severe sleep problems with a healthcare professional.'],recommended_for:['sleep','tired'],symbol:'☾'},
{slug:'boundary-builder',title:'Boundary Builder',category:'relationships',summary:'Turn “this is too much” into a clear recovery-protecting boundary.',steps:['Name the situation costing you stability.','Decide what you will do—not what you will force another person to do.','Use a short, clear sentence.','Plan how you will follow through.','Use support if safety or coercion is involved.'],recommended_for:['boundary','relationship','family'],symbol:'◇'},
{slug:'support-script',title:'Ask for Help Script',category:'connection',summary:'Make reaching out easier when you do not know what to say.',steps:['Choose a safe person.','Start with: “I do not need you to fix this.”','Say what is happening in one sentence.','Ask for one specific thing.','If that person cannot help, contact another support.'],recommended_for:['support','help','lonely'],symbol:'☎'},
{slug:'warning-sign-plan',title:'Early Warning Plan',category:'planning',summary:'Decide what to do when recovery starts drifting before a return to use.',steps:['List your earliest warning signs.','Choose the first support person you will contact.','Choose one place or situation you will avoid.','Name one recovery routine you will restart immediately.','Include professional or emergency support when needed.'],recommended_for:['warning','relapse','drift'],symbol:'◆'},
{slug:'after-use',title:'After a Return to Use',category:'planning',summary:'Respond to a return to use with safety and the next appropriate support step.',steps:['Get to a safer environment.','Do not drive or add substances to “even things out.”','Contact someone you trust.','Seek urgent medical help for overdose symptoms, breathing problems, loss of consciousness, severe illness, or other emergencies.','After immediate safety, reconnect with treatment or recovery support and review what happened without treating it as the end of recovery.'],recommended_for:['already used','relapse','return to use'],symbol:'↺'},
{slug:'one-task',title:'One-Task Reset',category:'planning',summary:'Reduce overwhelm by shrinking the day to one practical next step.',steps:['Write down what is competing for attention.','Circle the one thing that most affects safety or stability.','Break it into a 5–20 minute step.','Do only that step.','Reassess after it is complete.'],recommended_for:['overwhelmed','money','work','housing'],symbol:'1'},
{slug:'meeting-ready',title:'Get Ready for Support',category:'connection',summary:'Make attending a meeting, group, or appointment easier.',steps:['Confirm the time and location or link.','Plan transportation or a quiet place.','Decide whether to contact someone beforehand.','Bring one question if useful.','Afterward, note one thing you want to carry forward.'],recommended_for:['meeting','support','treatment'],symbol:'▤'},
{slug:'values-check',title:'Values Check',category:'values',summary:'Reconnect a hard decision with what matters to you.',steps:['Name the decision.','Name the value you want to protect.','Notice which option moves closer to that value.','Choose the smallest value-aligned action.','Revisit the decision later if you do not need to decide immediately.'],recommended_for:['purpose','values','decision'],symbol:'✦'},
{slug:'delay-decide',title:'Delay, Then Decide',category:'planning',summary:'Create time between an impulse and a decision.',steps:['If it is safe, delay the decision for 10 minutes.','Change your location or put distance between you and the impulse.','Use one grounding or connection tool.','Ask what the decision could cost tomorrow.','Decide again after the delay.'],recommended_for:['impulsive','urge','conflict'],symbol:'◷'}];
async function getTools(){try{const{data:r,error}=await sb.from('recovery_tools').select('*').eq('published',true).order('sort_order');if(!error&&r?.length)return r}catch(e){}return FALLBACK}
async function renderTools(cat='all'){GA.tools=await getTools();qa('[data-groupa-tool-cat]').forEach(b=>b.classList.toggle('active',b.dataset.groupaToolCat===cat));const rows=cat==='all'?GA.tools:GA.tools.filter(x=>x.category===cat),box=q('#groupAToolGrid');if(!box)return;box.innerHTML=rows.map(x=>`<article class="groupa-tool-card"><div class="sym">${esc(x.symbol||'◇')}</div><small>${esc(x.category)}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><button class="approved-link" data-groupa-tool="${esc(x.slug)}">Open →</button></article>`).join('');qa('[data-groupa-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.groupaTool))}
async function openTool(slug){if(!GA.tools.length)GA.tools=await getTools();const t=GA.tools.find(x=>x.slug===slug)||FALLBACK.find(x=>x.slug===slug);if(!t)return;GA.activeTool=t;txt('groupAToolDetailCat',String(t.category||'tool').toUpperCase());txt('groupAToolDetailTitle',t.title);txt('groupAToolDetailSummary',t.summary);q('#groupAToolSteps').innerHTML=(t.steps||[]).map((s,i)=>`<div class="groupa-tool-step"><span>${i+1}</span><p>${esc(s)}</p></div>`).join('');q('#groupAToolDetail').classList.remove('hidden');q('#groupAToolDetail').scrollIntoView({behavior:'smooth',block:'start'});if(currentUser)sb.from('tool_use_log').insert({user_id:currentUser.id,tool_slug:t.slug}).then(()=>{})}
async function completeTool(){if(!GA.activeTool)return;if(currentUser)await sb.from('tool_use_log').insert({user_id:currentUser.id,tool_slug:GA.activeTool.slug,completed_at:new Date().toISOString()});toast('Tool marked used.')}

async function loadPersonal(){if(!currentUser)return;try{const{data:r}=await sb.from('personalization_preferences').select('*').eq('user_id',currentUser.id).maybeSingle();if(r)GA.personal={enabled:r.enabled!==false,style:r.recommendation_style||'gentle',beliefVariants:r.belief_variants!==false}}catch(e){}if(q('#groupAPersonalizationEnabled'))q('#groupAPersonalizationEnabled').value=String(GA.personal.enabled);if(q('#groupAPersonalizationStyle'))q('#groupAPersonalizationStyle').value=GA.personal.style;if(q('#groupABeliefVariants'))q('#groupABeliefVariants').value=String(GA.personal.beliefVariants)}
async function savePersonal(){if(!currentUser)return;GA.personal={enabled:q('#groupAPersonalizationEnabled')?.value!=='false',style:q('#groupAPersonalizationStyle')?.value||'gentle',beliefVariants:q('#groupABeliefVariants')?.value!=='false'};await sb.from('personalization_preferences').upsert({user_id:currentUser.id,enabled:GA.personal.enabled,recommendation_style:GA.personal.style,belief_variants:GA.personal.beliefVariants},{onConflict:'user_id'});personalize()}
async function personalize(){await loadPersonal();let slug='grounding-54321',why='A grounding tool is a simple place to start when nothing more specific stands out.';if(GA.personal.enabled&&currentUser){try{const since=new Date();since.setDate(since.getDate()-21);const[g,c]=await Promise.all([sb.from('guided_responses').select('selected_choices,optional_reflection').eq('user_id',currentUser.id).gte('response_date',since.toISOString().slice(0,10)).order('response_date',{ascending:false}).limit(30),sb.from('daily_checkins').select('mood,stress,craving').eq('user_id',currentUser.id).gte('checkin_date',since.toISOString().slice(0,10)).order('checkin_date',{ascending:false}).limit(21)]);const s=((g.data||[]).flatMap(x=>x.selected_choices||[]).join(' ')+' '+(g.data||[]).map(x=>x.optional_reflection||'').join(' ')).toLowerCase(),cr=(c.data||[]).filter(x=>x.craving!=null),avg=cr.reduce((a,x)=>a+Number(x.craving),0)/Math.max(1,cr.length);const map=[[()=>avg>=6||/(craving|urge|substance|using)/.test(s),'craving-reset','Cravings or high-risk situations have appeared in your recent activity.'],[()=>/(lonely|isolation|alone)/.test(s),'connection-step','Connection may deserve a little more attention right now.'],[()=>/(angry|anger|irritable|conflict)/.test(s),'anger-pause','Slowing conflict down may be useful right now.'],[()=>/(sleep|tired|fatigue)/.test(s),'sleep-reset','Rest and sleep may deserve some protection.'],[()=>/(trigger|risky place|risky people)/.test(s),'trigger-review','A short trigger review may help you notice the pattern earlier.'],[()=>/(boundary|family|relationship)/.test(s),'boundary-builder','A recovery-protecting boundary may be worth practicing.'],[()=>/(overwhelmed|money|work|housing|legal)/.test(s),'one-task','There may be several things competing for your attention. One task is enough.'],[()=>/(purpose|values|meaning|future)/.test(s),'values-check','A values check may help connect recovery with the life you are building.']];const hit=map.find(x=>x[0]());if(hit){slug=hit[1];why=hit[2]}}catch(e){}}GA.recommended=slug;const t=(await getTools()).find(x=>x.slug===slug)||FALLBACK.find(x=>x.slug===slug);txt('groupAForYouTitle',t?.title||'One useful next step');txt('groupAForYouText',GA.personal.enabled?why:'Personalization is off. Lellee is showing a general recovery tool.');txt('groupAToolRecTitle',t?.title||'Recovery Tool');txt('groupAToolRecText',GA.personal.enabled?why:'Personalization is off. Browse any tool that fits.')}

async function renderLearn(view='recommended',topic=null){const p=phaseFor(daysInRecovery());txt('learnPhaseBadge',p.name.toUpperCase());txt('learnPhaseTitle',`Recommended for ${p.name}`);const box=view==='saved'?q('#savedLearningList'):view==='worksheets'?q('#worksheetList'):topic?q('#topicLearningList'):q('#recommendedLearningList');if(!box)return;try{let rows=[];if(view==='saved'&&currentUser){const{data:r}=await sb.from('saved_learning').select('content_item_id,content_items(*)').eq('user_id',currentUser.id).order('created_at',{ascending:false});rows=(r||[]).map(x=>x.content_items).filter(Boolean)}else{let qry=sb.from('content_items').select('*').eq('published',true);if(view==='worksheets')qry=qry.eq('content_type','worksheet');else if(topic)qry=qry.contains('tags',[topic]);else qry=qry.or(`phase_key.eq.${p.key},phase_key.is.null`);const{data:r}=await qry.order('day_number',{ascending:true}).limit(24);rows=r||[]}box.innerHTML=rows.length?rows.map(x=>`<article class="approved-learning-card"><div class="approved-learning-meta"><span>${esc((x.content_type||'lesson').replace('_',' '))}</span><em>${esc((x.phase_key||'all recovery').replace('_',' '))}</em></div><h3>${esc(x.title)}</h3><p>${esc(x.summary||'')}</p><div class="approved-learning-actions"><button class="approved-link" data-ga-learn-open="${x.id}">Open</button><button class="approved-link" data-ga-learn-save="${x.id}">Save</button></div></article>`).join(''):'<div class="approved-resource-empty"><b>No published items in this view yet.</b></div>';qa('[data-ga-learn-open]').forEach(b=>b.onclick=()=>openLearn(b.dataset.gaLearnOpen));qa('[data-ga-learn-save]').forEach(b=>b.onclick=()=>saveLearn(b.dataset.gaLearnSave))}catch(e){box.innerHTML='<div class="approved-resource-empty">Run the Group A SQL to activate the learning library.</div>'}}
async function openLearn(id){const{data:x,error}=await sb.from('content_items').select('*').eq('id',id).single();if(error||!x)return;GA.learn=x;txt('learningDetailType',String(x.content_type||'learning').toUpperCase());txt('learningDetailTitle',x.title);txt('learningDetailSummary',x.summary||'');let body=esc(x.body_markdown||'').replace(/\n\n/g,'</p><p>'),belief=beliefOption();if(belief)body+=`</p><div class="groupa-belief-note">${esc(belief)}</div><p>`;q('#learningDetailBody').innerHTML='<p>'+body+'</p>';showPage('learning-detail')}
async function saveLearn(id){if(!currentUser)return;const{error}=await sb.from('saved_learning').upsert({user_id:currentUser.id,content_item_id:id},{onConflict:'user_id,content_item_id'});if(error)return alert(error.message);toast('Saved for later.')}
async function completeLearn(){if(!currentUser||!GA.learn)return;const{error}=await sb.from('learning_progress').upsert({user_id:currentUser.id,content_item_id:GA.learn.id,status:'completed',completed_at:new Date().toISOString()},{onConflict:'user_id,content_item_id'});if(error)return alert(error.message);toast('Marked complete.')}

/* Preserve prior Journal Companion usability while Group B will harden the full app. */
async function ensureCollections(){if(!currentUser)return;try{let{data:r}=await sb.from('journal_collections').select('*').eq('user_id',currentUser.id).order('sort_order');if(!r?.length){await sb.from('journal_collections').insert([{user_id:currentUser.id,name:'Daily Journal',system_key:'daily',sort_order:10},{user_id:currentUser.id,name:"Things I'm Learning",system_key:'learning',sort_order:20},{user_id:currentUser.id,name:'Gratitude & Good Moments',system_key:'gratitude',sort_order:30}]);({data:r}=await sb.from('journal_collections').select('*').eq('user_id',currentUser.id).order('sort_order'))}GA.collections=r||[];if(q('#journalCollectionSelect'))q('#journalCollectionSelect').innerHTML=GA.collections.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(q('#journalFilterCollection'))q('#journalFilterCollection').innerHTML='<option value="">All collections</option>'+GA.collections.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}catch(e){}}
async function saveJournal(){const body=val('journalText');if(!currentUser||!body)return;await ensureCollections();const{error}=await sb.from('journal_entries').insert({user_id:currentUser.id,entry_date:todayKey(),title:val('journalTitleV2')||null,prompt_key:q('#journalPromptSelect')?.value||'custom',prompt_text:q('#journalPromptTitle')?.textContent||null,phase_key:phaseFor(daysInRecovery()).key,content:body,is_favorite:!!q('#journalFavoriteV2')?.checked,collection_id:q('#journalCollectionSelect')?.value||null,source:'digital',physical_volume:q('#journalPhysicalVolume')?.value||null,physical_page:val('journalPhysicalPage')||null,allow_recovery_story:!!q('#journalStoryOptInV2')?.checked});if(error)return alert(error.message);q('#journalText').value='';toast('Journal entry saved.');loadJournalEntries()}
async function loadJournalEntries(){if(!currentUser)return;await ensureCollections();try{const{data:r}=await sb.from('journal_entries').select('*').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(100);GA.journalRows=r||[];const box=q('#journalEntryCards');if(box)box.innerHTML=GA.journalRows.map(x=>`<article class="approved-journal-entry-card"><small>${x.entry_date}</small><h3>${esc(x.title||x.prompt_text||'Journal entry')}</h3><p>${esc(x.content).slice(0,260)}</p></article>`).join('')||'<div class="approved-resource-empty">No entries yet.</div>'}catch(e){}}

function bind(){q('#openGuidedDay2')?.addEventListener('click',()=>{renderGuided();showPage('guided-day')});q('#openJourneyToday')?.addEventListener('click',()=>{renderGuided();showPage('guided-day')});q('#openJourneyHistory')?.addEventListener('click',()=>{q('#journeyHistoryPanel')?.classList.toggle('hidden');renderHistory()});q('#saveGuidedJourneyA')?.addEventListener('click',saveGuided);qa('[data-groupa-tool-cat]').forEach(b=>b.addEventListener('click',()=>renderTools(b.dataset.groupaToolCat)));q('#groupACloseTool')?.addEventListener('click',()=>q('#groupAToolDetail')?.classList.add('hidden'));q('#groupACompleteTool')?.addEventListener('click',completeTool);q('#groupAOpenRecommended')?.addEventListener('click',()=>openTool(GA.recommended));q('#groupAForYouAction')?.addEventListener('click',()=>{showPage('tools');setTimeout(()=>openTool(GA.recommended),80)});q('#saveSettings')?.addEventListener('click',savePersonal);qa('[data-learn-tab]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.learnTab;qa('[data-learn-tab]').forEach(x=>x.classList.toggle('active',x===b));q('#learnRecommendedPanel')?.classList.toggle('hidden',v!=='recommended');q('#learnTopicsPanel')?.classList.toggle('hidden',v!=='topics');q('#learnSavedPanel')?.classList.toggle('hidden',v!=='saved');q('#learnWorksheetsPanel')?.classList.toggle('hidden',v!=='worksheets');renderLearn(v)}));qa('[data-topic]').forEach(b=>b.addEventListener('click',()=>renderLearn('topic',b.dataset.topic)));q('#saveLearningItem')?.addEventListener('click',()=>GA.learn&&saveLearn(GA.learn.id));q('#markLearningComplete')?.addEventListener('click',completeLearn)}
async function refresh(){await loadPersonal();await Promise.allSettled([renderJourney(),renderTools(),personalize(),renderLearn('recommended'),ensureCollections()])}
GA.saveJournal=saveJournal;GA.loadJournalEntries=loadJournalEntries;window.LelleeGroupA=GA;bind();let tries=0;const wait=setInterval(()=>{tries++;if(currentUser){clearInterval(wait);refresh()}else if(tries>30)clearInterval(wait)},200);const oldShow=showPage;showPage=function(name){oldShow(name);if(name==='journey')renderJourney();if(name==='guided-day')renderGuided();if(name==='tools')renderTools();if(name==='learn')renderLearn('recommended');if(name==='journal')loadJournalEntries()};
})();
