-- Lellee Agent Access Control - staged migration
-- Do not expose service_role credentials to the browser.
-- Review in a staging Supabase project before production application.

create table if not exists public.lellee_agent_registry (
  id uuid primary key default gen_random_uuid(),
  agent_key text not null unique,
  display_name text not null,
  status text not null default 'disabled' check (status in ('active','disabled','retired')),
  capabilities text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lellee_agent_audit_log (
  id bigint generated by default as identity primary key,
  agent_key text not null,
  user_id uuid,
  capability text not null,
  resource_type text,
  resource_id text,
  decision text not null check (decision in ('allow','deny')),
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.lellee_agent_registry enable row level security;
alter table public.lellee_agent_audit_log enable row level security;

-- No client/browser policies are intentionally created.
-- Result: anon/authenticated browser sessions cannot read or mutate these tables by default.
-- Trusted server-side functions may access them using a protected server credential.

create or replace function public.lellee_agent_capability_allowed(
  p_agent_key text,
  p_capability text
) returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.lellee_agent_registry a
    where a.agent_key = p_agent_key
      and a.status = 'active'
      and p_capability = any(a.capabilities)
  );
$$;

revoke all on function public.lellee_agent_capability_allowed(text,text) from public;
revoke all on function public.lellee_agent_capability_allowed(text,text) from anon;
revoke all on function public.lellee_agent_capability_allowed(text,text) from authenticated;

-- Grant EXECUTE only to the trusted server role used by Lellee's backend/Edge Function.
