begin;
delete from public.professional_assessment_items
where module_id in (
 select m.id from public.professional_course_modules m
 join public.professional_courses c on c.id=m.course_id
 where c.course_key='coaching_foundations'
   and m.module_key in ('scope_role_boundaries','ethics_privacy_consent','trauma_cultural_responsiveness','communication_skills')
);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='scope_role_boundaries'),1,'multiple_choice','A participant asks the coach to diagnose a mental-health condition. What is the best response?','["Provide a diagnosis based on the conversation.","Explain that diagnosis is outside coaching scope and support referral to a qualified clinician if the participant wants an evaluation.","Ignore the request completely.","Search symptoms online and make a best guess."]'::jsonb,'{"index":1}'::jsonb,'Diagnosis is outside coaching scope; responsible coaching names the boundary and supports appropriate referral.','ICF ethical role clarity','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='scope_role_boundaries'),2,'scenario','A participant asks whether a housing notice is legally valid. What should the coach do?','["Interpret the notice and give a legal conclusion.","Help organize questions, deadlines, and next steps while referring legal interpretation to qualified legal help.","Tell the participant to ignore the notice.","Contact the housing provider and threaten legal action."]'::jsonb,'{"index":1}'::jsonb,'A coach can help organize action without providing individualized legal advice.','ICF ethical scope','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='scope_role_boundaries'),3,'multiple_choice','Which statement best reflects participant ownership in coaching?','["The coach decides the plan because the coach has more experience.","The participant chooses goals and actions; the coach helps clarify, structure, and review them.","The sponsor always decides the participant''s goals.","The coach should avoid all structure."]'::jsonb,'{"index":1}'::jsonb,'Coaching is collaborative and participant-centered rather than directive or passive.','ICF Core Competencies','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='scope_role_boundaries'),4,'multiple_choice','A coach has a financial interest in a company they are considering recommending. What is the strongest ethical response?','["Recommend it without mentioning the interest.","Disclose the relevant conflict and consider alternatives that protect participant choice.","Avoid all referrals forever.","Tell the participant the company is objectively the best."]'::jsonb,'{"index":1}'::jsonb,'Relevant conflicts should be disclosed and managed so they do not distort participant choice.','ICF Code of Ethics','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='scope_role_boundaries'),5,'scenario','A participant develops acute physical symptoms during a session. What should take priority?','["Finish the coaching goal first.","Treat the situation as a possible medical concern and direct the participant to appropriate emergency medical help rather than diagnosing it.","Teach a coping skill and wait until the next session.","Diagnose anxiety."]'::jsonb,'{"index":1}'::jsonb,'A coach should not diagnose acute medical symptoms; urgent physical concerns require medical evaluation.','Scope and emergency boundary','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='scope_role_boundaries'),6,'multiple_choice','Which marketing statement is appropriate for a person who completed Lellee training but holds no professional license?','["Licensed Lellee Therapist","State-Certified Recovery Clinician","Completed Lellee Coaching Foundations training","Board-Certified Behavioral Health Specialist"]'::jsonb,'{"index":2}'::jsonb,'Course completion must not be represented as a professional license or clinical credential.','Truthful representation principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='scope_role_boundaries'),7,'multiple_choice','When can lived experience be useful in coaching?','["Whenever the coach wants to tell a long personal story.","When brief, purposeful self-disclosure benefits the participant and does not make the coach''s experience the template.","Only if the participant has exactly the same background.","Never under any circumstances."]'::jsonb,'{"index":1}'::jsonb,'Lived experience can support empathy, but participant needs remain central.','Participant-centered practice','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='scope_role_boundaries'),8,'scenario','A coach is asked to coach a close relative while also reporting progress to the relative''s employer. What is the main concern?','["There is no concern because family knows the participant well.","Multiple roles and conflicts may undermine free choice and confidentiality, so the coach should disclose and determine whether the arrangement can be ethically managed.","The coach should accept because it creates more revenue.","The coach should secretly report only positive information."]'::jsonb,'{"index":1}'::jsonb,'Multiple relationships and sponsor pressures can create conflicts that require disclosure and management.','ICF Code of Ethics','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='ethics_privacy_consent'),1,'multiple_choice','Which item belongs in a clear coaching agreement?','["A promise that all results are guaranteed.","Purpose, communication expectations, privacy expectations, fees or sponsorship, and how the relationship can change or end.","Permission for the coach to share anything they find interesting.","A clinical treatment plan."]'::jsonb,'{"index":1}'::jsonb,'Informed agreement requires clear expectations about the relationship and its boundaries.','ICF Code of Ethics','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='ethics_privacy_consent'),2,'scenario','A participant shares one private journal entry with the coach for a specific purpose. What should happen next?','["The coach may now copy the entire journal indefinitely.","The coach should use only the shared material for the agreed purpose and not assume access to other private entries.","The coach should send it to family members.","The coach should publish an anonymized screenshot."]'::jsonb,'{"index":1}'::jsonb,'Sharing should remain purpose-limited and participant-directed.','ICF confidentiality and Lellee privacy boundary','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='ethics_privacy_consent'),3,'multiple_choice','Which statement about HIPAA is most accurate for consumer health apps?','["Every health-related app is automatically covered by HIPAA.","HIPAA generally applies to covered entities and business associates; many consumer apps are not covered, though other privacy laws and duties may apply.","If HIPAA does not apply, privacy does not matter.","HIPAA applies only when a user pays a subscription."]'::jsonb,'{"index":1}'::jsonb,'HHS notes that many consumer apps are outside HIPAA, while FTC and other rules may still apply.','HHS health app privacy guidance','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='ethics_privacy_consent'),4,'scenario','A coach wants to keep participant notes in a personal cloud document because it is convenient. What is the best response?','["Use any tool as long as the coach remembers the password.","Use approved systems and avoid moving sensitive information into uncontrolled storage.","Email the document to several accounts as backup.","Take screenshots and keep them in a phone photo library."]'::jsonb,'{"index":1}'::jsonb,'Sensitive health and recovery information should be minimized and kept in approved systems.','FTC/HHS privacy guidance','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='ethics_privacy_consent'),5,'multiple_choice','A participant''s employer sponsors coaching. What should be clarified before coaching begins?','["The employer automatically receives all notes.","What, if anything, may be shared with the sponsor and what remains private.","The participant has no privacy because the employer pays.","Only the employer chooses all goals."]'::jsonb,'{"index":1}'::jsonb,'Sponsor arrangements require transparent agreements about information sharing and roles.','ICF Code of Ethics','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='ethics_privacy_consent'),6,'multiple_choice','A participant gives a powerful success story. Before using it in marketing, the coach should:','["Post it immediately because it is positive.","Obtain appropriate permission and avoid exploiting vulnerable or identifiable information.","Remove the first name and assume consent.","Trade the story for a discount without explaining how it will be used."]'::jsonb,'{"index":1}'::jsonb,'Testimonials and identifiable stories require truthful, informed, ethical use.','ICF Code of Ethics','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='ethics_privacy_consent'),7,'scenario','A coach accidentally sends a participant''s recovery note to the wrong recipient. What is the best immediate response?','["Delete the sent message and tell no one.","Stop further disclosure, preserve the facts, and follow the organization''s privacy or incident-response process.","Ask the recipient to promise secrecy and consider the issue resolved.","Change the participant''s name in the database."]'::jsonb,'{"index":1}'::jsonb,'Privacy incidents should be contained and escalated through the approved process, not concealed.','FTC health-data breach principles','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='ethics_privacy_consent'),8,'multiple_choice','What does data minimization mean in coaching?','["Collect everything in case it becomes useful someday.","Collect and retain only information reasonably needed for the coaching purpose and applicable obligations.","Never document anything.","Delete information immediately after every session regardless of requirements."]'::jsonb,'{"index":1}'::jsonb,'Purpose-limited collection reduces unnecessary exposure of sensitive information.','Privacy-by-design principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='trauma_cultural_responsiveness'),1,'multiple_choice','A trauma-informed approach requires a coach to:','["Diagnose trauma before setting goals.","Create safety, transparency, collaboration, choice, and practices that avoid retraumatization.","Ask every participant for a detailed trauma history.","Avoid all difficult topics."]'::jsonb,'{"index":1}'::jsonb,'SAMHSA emphasizes safety, trust, collaboration, empowerment, and resistance to retraumatization.','SAMHSA trauma-informed approach','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='trauma_cultural_responsiveness'),2,'scenario','A participant becomes quiet when asked about family history. What is the strongest coaching response?','["Insist on an answer because the question is on the intake form.","Acknowledge the pause, offer choice about whether to continue, and explain why the question was asked if it remains relevant.","Assume the participant is hiding something.","End coaching immediately."]'::jsonb,'{"index":1}'::jsonb,'Choice and transparency reduce coercion and support safety.','SAMHSA trauma principles','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='trauma_cultural_responsiveness'),3,'multiple_choice','Cultural humility is best demonstrated by:','["Memorizing stereotypes about every culture.","Asking, listening, and remaining open to correction rather than assuming what a participant values.","Treating culture as irrelevant.","Using the coach''s own family norms as the standard."]'::jsonb,'{"index":1}'::jsonb,'Cultural responsiveness requires curiosity and attention to participant context, identity, and values.','ICF Core Competencies','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='trauma_cultural_responsiveness'),4,'scenario','A court-referred participant agrees with every suggestion but rarely follows through. What should the coach consider?','["The participant is lazy.","Power differences may be producing surface agreement; restate choices and explore what the participant actually wants and can do.","Increase pressure until compliance improves.","Report defiance without discussing it."]'::jsonb,'{"index":1}'::jsonb,'Coercive contexts can affect free choice; collaboration and voice should be reinforced.','Trauma-informed collaboration principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='trauma_cultural_responsiveness'),5,'multiple_choice','Which is the best use of coach self-disclosure?','["A long story showing that the coach overcame the same problem.","A brief, relevant disclosure used only if it serves the participant and returns focus to them.","Frequent examples proving the coach''s choices are better.","Self-disclosure whenever silence feels uncomfortable."]'::jsonb,'{"index":1}'::jsonb,'Self-disclosure should not shift the center of the coaching relationship to the coach.','Participant-centered practice','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='trauma_cultural_responsiveness'),6,'scenario','A participant misses two sessions after discussing a painful transition. A trauma-informed response begins with:','["A warning that they will be discharged.","Curiosity about what made attendance difficult and what would make contact feel more workable.","A conclusion that they are not motivated.","A demand for details about the transition."]'::jsonb,'{"index":1}'::jsonb,'Trauma-informed practice avoids punitive assumptions and seeks collaboration.','SAMHSA trauma-informed approach','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='trauma_cultural_responsiveness'),7,'multiple_choice','Which statement is most consistent with empowerment, voice, and choice?','["You need to do this because I know what works.","Here are two options we can explore, and you can decide whether either fits.","If you cared enough, you would follow my plan.","I already told your family what you should do."]'::jsonb,'{"index":1}'::jsonb,'The participant''s voice and choices should remain central.','SAMHSA trauma principles','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='trauma_cultural_responsiveness'),8,'scenario','A participant begins describing painful past events and becomes increasingly distressed. What should the coach do?','["Encourage deeper processing to achieve a breakthrough.","Slow down, restore choice, clarify coaching limits, and refer for trauma treatment when indicated.","Interpret the meaning of the experience.","Ask for more detail for the coaching record."]'::jsonb,'{"index":1}'::jsonb,'Coaching should not become trauma processing or psychotherapy.','Scope and trauma-informed boundaries','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='communication_skills'),1,'multiple_choice','Which question is most likely to invite reflection?','["Did you apply for the job?","Why didn''t you listen to me?","What would make the next step realistic this week?","You know you should call them, right?"]'::jsonb,'{"index":2}'::jsonb,'Open questions invite participant thinking rather than defensiveness or compliance.','ICF active listening and evoking awareness','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='communication_skills'),2,'multiple_choice','A useful reflection does what?','["Proves the coach is correct.","Offers a concise understanding of what the participant communicated and allows correction.","Changes the subject quickly.","Provides a diagnosis."]'::jsonb,'{"index":1}'::jsonb,'Reflecting and summarizing support clarity and deeper listening.','ICF Core Competencies','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='communication_skills'),3,'scenario','A participant says they want change but are afraid of losing important social connections. What is the best response?','["You obviously need new friends.","It sounds like change matters to you, and you are also worried about what it could cost socially. What feels most important to explore first?","If you wanted change enough, you would do it.","Let''s ignore the fear and make a contract."]'::jsonb,'{"index":1}'::jsonb,'A reflective, autonomy-supportive response explores ambivalence without confrontation.','SAMHSA TIP 35','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='communication_skills'),4,'multiple_choice','Before offering advice or information, a coach should generally:','["Assume permission because the participant paid.","Ask permission or check whether the participant wants information.","Give the advice quickly before the participant changes topics.","Wait until the participant fails."]'::jsonb,'{"index":1}'::jsonb,'Permission-based information sharing supports autonomy and partnership.','Motivational and coaching communication principles','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='communication_skills'),5,'multiple_choice','An effective affirmation focuses on:','["Generic praise regardless of behavior.","A genuine effort, value, strength, or choice demonstrated by the participant.","The coach''s approval of the participant as a person.","Comparing the participant favorably to others."]'::jsonb,'{"index":1}'::jsonb,'Specific affirmations reinforce participant strengths without creating dependence on praise.','SAMHSA motivational communication','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='communication_skills'),6,'scenario','A participant pauses for several seconds after a difficult question. The coach should:','["Immediately fill the silence with a new question.","Allow reasonable silence and remain present unless the participant signals they need something else.","Assume the participant is refusing to cooperate.","Start explaining the answer."]'::jsonb,'{"index":1}'::jsonb,'Silence can support reflection and should not automatically be treated as a problem.','ICF presence/listening','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='communication_skills'),7,'multiple_choice','The “righting reflex” refers to:','["Correcting spelling in notes.","The urge to fix, persuade, or argue someone into change.","Reviewing a goal after it is completed.","Checking that a referral phone number is correct."]'::jsonb,'{"index":1}'::jsonb,'Motivational guidance cautions against reflexively fixing or arguing for change.','SAMHSA TIP 35','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='communication_skills'),8,'scenario','A participant becomes tearful while discussing a job loss. What keeps the interaction within coaching scope?','["Analyzing childhood origins of the emotion.","Acknowledging the emotion, staying present, asking what support is useful now, and referring if treatment or crisis care is needed.","Telling them to stop crying so the session can continue.","Diagnosing depression."]'::jsonb,'{"index":1}'::jsonb,'Emotion can be acknowledged without turning coaching into psychotherapy or diagnosis.','ICF role boundary','internal_review',true);
commit;