begin;
delete from public.professional_assessment_items
where module_id in (
 select m.id from public.professional_course_modules m
 join public.professional_courses c on c.id=m.course_id
 where c.course_key='coaching_foundations'
   and m.module_key in ('goals_accountability','documentation_shared_progress','risk_referral_escalation')
);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='goals_accountability'),1,'multiple_choice','Who ultimately owns the coaching goal?','["The coach","The participant","The sponsor in every case","The software platform"]'::jsonb,'{"index":1}'::jsonb,'Coaching goals are participant-led even when the coach provides structure.','ICF facilitates client growth','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='goals_accountability'),2,'scenario','A participant rates confidence in completing a five-step plan as 2 out of 10. What is the best next move?','["Tell them to be more confident.","Explore what would make the step smaller, more realistic, or more personally meaningful.","Add more steps so the plan looks complete.","Warn them that failure will be documented."]'::jsonb,'{"index":1}'::jsonb,'Low confidence is information that the plan may need adjustment.','Participant-centered action planning','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='goals_accountability'),3,'multiple_choice','Which is the strongest next action?','["Get my life together.","Someday I will find a better job.","By Thursday, identify three jobs that fit my schedule and save them for review.","Be more motivated."]'::jsonb,'{"index":2}'::jsonb,'A concrete, time-linked action is easier to attempt and review.','ICF action planning','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='goals_accountability'),4,'scenario','A participant does not complete an agreed housing call. What should accountability sound like?','["You failed the assignment.","What got in the way, what did you learn, and what next step feels workable now?","I will call for you without asking.","You cannot continue coaching until you comply."]'::jsonb,'{"index":1}'::jsonb,'Accountability reviews barriers and learning without shame or coercion.','ICF client growth','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='goals_accountability'),5,'multiple_choice','A backup plan is useful because:','["It guarantees success.","It gives the participant an alternative when a predictable barrier occurs.","It lets the coach decide everything in advance.","It replaces the participant''s goal."]'::jsonb,'{"index":1}'::jsonb,'Barrier planning makes action more resilient without removing participant ownership.','Action-planning principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='goals_accountability'),6,'multiple_choice','When a goal changes, the coach should:','["Treat the change as noncompliance.","Clarify the new agreement and document the updated goal.","Keep pushing the original goal.","End the relationship automatically."]'::jsonb,'{"index":1}'::jsonb,'Coaching adapts to participant priorities and records the updated agreement.','ICF partnership','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='goals_accountability'),7,'scenario','A participant succeeds in attending three appointments. What response best supports self-efficacy?','["You did it because I kept reminding you.","What did you do that helped you make those appointments happen?","You should be able to do this every time now.","Good job; let''s not discuss it further."]'::jsonb,'{"index":1}'::jsonb,'Helping participants identify their own effective actions supports durable learning.','ICF facilitates growth','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='goals_accountability'),8,'multiple_choice','Which accountability method is inappropriate?','["Calendar reminders chosen by the participant.","A progress review.","Threatening to withhold essential safety support because a goal was missed.","Breaking a large task into steps."]'::jsonb,'{"index":2}'::jsonb,'Essential safety support should not be used as leverage for compliance.','Ethical coaching principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='documentation_shared_progress'),1,'multiple_choice','Which note is most objective?','["Client is manipulative.","Participant reported sleeping about three hours last night and asked to shorten today''s action plan.","Client is clearly manic.","Client is lazy about goals."]'::jsonb,'{"index":1}'::jsonb,'Objective notes distinguish reported or observed facts from diagnostic or judgmental conclusions.','Documentation principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='documentation_shared_progress'),2,'scenario','A coach can technically access a participant''s private journal. What should the coach do?','["Read it to understand the participant better.","Use only material the participant deliberately shares through the approved mechanism.","Copy it into coaching notes for safekeeping.","Ask another coach to review it."]'::jsonb,'{"index":1}'::jsonb,'Technical access does not equal participant authorization to use private journal content.','Lellee privacy boundary','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='documentation_shared_progress'),3,'multiple_choice','Which item is usually appropriate for a coaching note?','["Every sensitive detail disclosed during the session.","The agreed goal, action steps, relevant resource or referral, and follow-up.","Speculation about personality disorders.","Unverified statements from family members presented as fact."]'::jsonb,'{"index":1}'::jsonb,'Documentation should be purpose-relevant and limited.','Privacy and coaching documentation principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='documentation_shared_progress'),4,'scenario','A participant misses an appointment after a setback. Which wording is best?','["Noncompliant participant failed to attend.","Participant did not attend the scheduled session; follow-up message sent through the approved channel.","Participant is sabotaging progress.","Participant lacks motivation."]'::jsonb,'{"index":1}'::jsonb,'Neutral, factual language avoids stigma and unsupported conclusions.','Objective documentation','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='documentation_shared_progress'),5,'multiple_choice','Why should consumer health and recovery information be minimized even when HIPAA may not apply?','["Because such information can still be sensitive and other privacy laws or promises may apply.","Because no digital system may store health information.","Because HIPAA automatically covers every app.","Because coaches are never allowed to document goals."]'::jsonb,'{"index":0}'::jsonb,'HHS and FTC guidance show that non-HIPAA consumer health data can still carry significant privacy obligations.','HHS/FTC health data guidance','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='documentation_shared_progress'),6,'multiple_choice','If a coaching note contains an error, the coach should:','["Delete all related records secretly.","Use the approved correction process so the change is transparent.","Change the date to make the record look correct.","Create a second conflicting note and say nothing."]'::jsonb,'{"index":1}'::jsonb,'Transparent correction preserves record integrity.','Documentation integrity principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='documentation_shared_progress'),7,'scenario','A safety escalation occurs. Which documentation is most appropriate?','["A long theory about why the participant is in crisis.","What the participant reported, observable facts, the resource or emergency action used, required notifications, and follow-up.","A promise that the situation is resolved.","Only the coach''s emotional reaction."]'::jsonb,'{"index":1}'::jsonb,'Safety documentation should focus on facts, actions, and handoff rather than diagnosis.','Safety documentation principle','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='documentation_shared_progress'),8,'multiple_choice','Which phrase should usually be replaced with a more objective description?','["Participant requested a housing referral.","Participant chose to postpone the job-search goal.","Participant was manipulative and resistant.","Participant agreed to call the clinic tomorrow."]'::jsonb,'{"index":2}'::jsonb,'Judgmental labels add risk without improving continuity.','Objective documentation','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='risk_referral_escalation'),1,'multiple_choice','What is 988 primarily designed for?','["Behavioral-health crisis support, including emotional distress and substance-use crisis support.","Routine billing questions.","Immediate fire response.","Legal representation."]'::jsonb,'{"index":0}'::jsonb,'SAMHSA identifies 988 as a behavioral-health crisis resource.','SAMHSA 988 guidance','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='risk_referral_escalation'),2,'multiple_choice','What is 911 primarily designed for in this context?','["Long-term coaching.","Immediate physical danger, medical emergencies, and situations needing urgent physical intervention.","Weekly goal review.","Finding a therapist."]'::jsonb,'{"index":1}'::jsonb,'SAMHSA distinguishes 911 for urgent physical danger and medical emergencies.','SAMHSA 988/911 guidance','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='risk_referral_escalation'),3,'scenario','A participant appears to be in immediate physical danger during a session. What should the coach do?','["Continue the coaching agenda and check in tomorrow.","Activate the appropriate emergency response according to policy.","Ask the participant to journal first.","Focus only on the original goal."]'::jsonb,'{"index":1}'::jsonb,'Immediate physical danger requires emergency response rather than ordinary coaching.','SAMHSA 988/911 guidance','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='risk_referral_escalation'),4,'scenario','A participant says they are in severe emotional distress but there is no immediate physical danger. What is the appropriate coaching action?','["Ignore it because it is not physical.","Pause ordinary coaching, take the concern seriously, and support connection to 988 or another approved crisis resource while following Lellee safety protocol.","Provide a diagnosis.","Promise absolute confidentiality and take no further action."]'::jsonb,'{"index":1}'::jsonb,'988 provides behavioral-health crisis support when immediate emergency response is not required.','SAMHSA crisis guidance','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='risk_referral_escalation'),5,'scenario','A participant appears to have a possible overdose or another acute medical emergency. What should happen?','["Start a goal-planning exercise.","Use emergency medical services according to protocol rather than treating it as a coaching issue.","Wait for the next coaching appointment.","Ask whether they want a referral next week."]'::jsonb,'{"index":1}'::jsonb,'Acute medical emergencies require emergency medical response.','SAMHSA 988 FAQ','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='risk_referral_escalation'),6,'multiple_choice','A coach''s role in crisis is to:','["Conduct a full clinical assessment and diagnose the condition.","Recognize concerning information, pause ordinary coaching, route to the appropriate crisis or emergency resource, and follow policy.","Guarantee the participant will be safe.","Provide medical treatment."]'::jsonb,'{"index":1}'::jsonb,'Coaches route and escalate rather than substitute for crisis or medical professionals.','Scope and crisis boundary','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='risk_referral_escalation'),7,'scenario','A participant discloses possible abuse of a dependent adult. The coach is unsure of reporting duties in that jurisdiction. What is the best response?','["Make up a legal rule based on another state.","Follow Lellee''s escalation process and obtain appropriate supervision or legal guidance about applicable reporting duties while addressing immediate safety.","Promise never to tell anyone.","Post the question publicly with identifying details."]'::jsonb,'{"index":1}'::jsonb,'Reporting duties vary; coaches should follow policy and applicable law rather than improvise legal conclusions.','Ethical and legal boundary','internal_review',true);
insert into public.professional_assessment_items(module_id,item_order,item_type,prompt,choices,correct_answer,rationale,source_note,review_status,active)
    values((select m.id from public.professional_course_modules m join public.professional_courses c on c.id=m.course_id where c.course_key='coaching_foundations' and m.module_key='risk_referral_escalation'),8,'multiple_choice','After a crisis handoff, the best coaching documentation includes:','["Only “crisis resolved.”","Reported or observed facts, action taken, resource or emergency contact used, required notifications, and planned follow-up.","A psychiatric diagnosis.","A detailed account of unrelated personal history."]'::jsonb,'{"index":1}'::jsonb,'Crisis notes should document facts and response without exceeding role.','Safety documentation principle','internal_review',true);
update public.professional_courses set assessment_review_status='internal_review',status='draft',checkout_enabled=false,updated_at=now() where course_key='coaching_foundations';
commit;