begin;
update public.professional_course_modules set content_md='# Scope, Role & Professional Boundaries

Professional coaching is a collaborative, participant-centered process. The coach helps a participant clarify goals, notice options, make decisions, plan manageable actions, and review progress. The participant remains the decision-maker. Coaching can be practical and structured without becoming therapy, medical treatment, legal advice, case management, benefits eligibility determination, emergency response, or another regulated service.

A strong coaching agreement makes the role clear before difficult situations arise. Explain what coaching can help with, what it cannot provide, how information is handled, what communication channels are used, how goals are chosen, and what happens when a need falls outside the coaching relationship. Do not use titles, credentials, or claims that imply a license or authority you do not hold.

Use a three-part boundary check when a request becomes complicated. First, ask whether the request fits the purpose of coaching. Second, ask whether you have the training and authority to respond. Third, ask whether delay or a wrong answer could create meaningful harm. If the answer points outside coaching, name the boundary plainly and help the participant connect with an appropriate qualified resource. Referral is not abandonment; it is part of responsible coaching.

Coaches may share observations, ask questions, offer educational information, and help organize next steps, but should avoid taking over the participant''s choices. Advice should not be disguised as a question. When a participant wants the coach to decide for them, return ownership respectfully: clarify the options, the participant''s priorities, and the next action they are willing to choose.

Boundaries also apply to relationships and conflicts of interest. A coach should notice when financial interests, dual roles, personal relationships, or pressure from another party could interfere with the participant''s interests or free choice. Disclose relevant conflicts, reset the agreement when needed, and decline or transfer work when the conflict cannot be managed responsibly.',source_refs='[{"title":"ICF Code of Ethics (effective April 1, 2025)","url":"https://coachingfederation.org/credentialing/coaching-ethics/icf-code-of-ethics/"},{"title":"2025 ICF Core Competencies","url":"https://coachingfederation.org/credentialing/coaching-competencies/icf-core-competencies/"},{"title":"ICF Criteria for Assessing PCC Credential","url":"https://coachingfederation.org/credentialing/performance-evaluations/criteria-for-assessing-pcc/"}]'::jsonb,practice_requirements='["Classify ten sample requests as coaching, coaching-with-referral, or outside scope and explain why.","Rewrite a service description so it accurately describes coaching without implying therapy, legal services, case management, or licensure."]'::jsonb,review_status='internal_review',updated_at=now()
          where module_key='scope_role_boundaries' and course_id=(select id from public.professional_courses where course_key='coaching_foundations');
update public.professional_course_modules set content_md='# Ethics, Privacy & Informed Consent

Ethical coaching starts with a clear agreement. A participant should know who the coach is, the purpose of the relationship, fees or sponsorship if relevant, expected communication, recordkeeping, confidentiality expectations, foreseeable limits on privacy, and how either party can end or change the coaching relationship. Consent is an ongoing process, not a one-time checkbox. If the purpose of coaching changes, revisit the agreement.

Confidentiality should be treated as a core trust obligation. Do not casually discuss a participant''s situation with relatives, employers, referral partners, other clients, or social media audiences. Share only what the participant has authorized or what applicable law and safety policy require. Within Lellee, private journal material is not automatically coach material. A participant should deliberately choose what progress, goals, or journal-derived information to share.

Health and recovery information deserves heightened care even when HIPAA does not apply. HHS explains that many consumer health apps are not covered by HIPAA unless they are offered by or on behalf of a HIPAA-regulated entity. That does not mean the information is unprotected or unimportant; the FTC Act, the FTC Health Breach Notification Rule, state law, contracts, and privacy promises may apply. Never tell a participant that information is “HIPAA protected” unless the actual relationship and system have been confirmed to fall under HIPAA.

Use data minimization: collect and record what is genuinely needed for the coaching purpose, not everything that is interesting. Avoid copying sensitive information into messages, notes, or external tools without a clear purpose and authorization. Use approved systems rather than personal email, uncontrolled spreadsheets, screenshots, or shared devices when those methods create unnecessary exposure.

Ethics also includes conflicts of interest, truthful marketing, respectful conduct, and accurate representation of qualifications. Testimonials, participant stories, recordings, and identifiable examples require appropriate permission. A participant''s vulnerability is not marketing content. If a privacy mistake occurs, stop further disclosure, preserve facts, notify the appropriate internal contact, and follow the incident-response process rather than trying to hide or privately “fix” the event.',source_refs='[{"title":"ICF Code of Ethics (effective April 1, 2025)","url":"https://coachingfederation.org/credentialing/coaching-ethics/icf-code-of-ethics/"},{"title":"2025 ICF Core Competencies","url":"https://coachingfederation.org/credentialing/coaching-competencies/icf-core-competencies/"},{"title":"HHS Consumer Health App Privacy Guidance","url":"https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/cell-phone-hipaa/index.html"},{"title":"FTC Health Breach Notification Rule","url":"https://www.ftc.gov/legal-library/browse/rules/health-breach-notification-rule"}]'::jsonb,practice_requirements='["Draft a plain-language coaching agreement checklist covering role, communication, privacy, fees, records, sharing, and ending the relationship.","Review five documentation or sharing examples and identify which information is unnecessary, unauthorized, or too sensitive for the proposed channel."]'::jsonb,review_status='internal_review',updated_at=now()
          where module_key='ethics_privacy_consent' and course_id=(select id from public.professional_courses where course_key='coaching_foundations');
update public.professional_course_modules set content_md='# Trauma-Informed & Culturally Responsive Engagement

Trauma-informed coaching does not mean diagnosing trauma or asking people to retell traumatic experiences. SAMHSA describes a trauma-informed approach as one that recognizes the widespread impact of trauma, notices possible signs, integrates trauma knowledge into practice, and actively seeks to avoid retraumatization. Core principles include safety, trustworthiness and transparency, peer support, collaboration and mutuality, empowerment, voice and choice, and attention to cultural, historical, and gender issues.

In coaching, those principles translate into practical behavior. Explain what will happen before asking sensitive questions. Offer choices where possible. Ask permission before moving into an emotionally charged topic. Do not force disclosure to prove commitment. Avoid punitive responses when a participant cancels, shuts down, becomes quiet, changes a goal, or needs more time. Curiosity is safer than assumption.

Cultural responsiveness requires more than being polite. A participant''s identity, language, family structure, community, faith or spirituality, disability, socioeconomic context, migration history, gender, race, and prior experiences with institutions can shape what support feels safe and useful. The coach does not need to be an expert in every culture; the coach does need humility, willingness to learn, and the discipline to ask rather than assume.

Power differences matter. A participant may feel pressure to agree with someone perceived as an authority figure, especially when coaching is connected to an employer, program, court, housing provider, or family member. Re-state the participant''s choices, distinguish coaching from compliance monitoring, and be transparent about any information that may be shared with a sponsor.

Lived experience can strengthen empathy but should not become a template imposed on someone else. A coach may use brief, purposeful self-disclosure when it benefits the participant and does not shift the focus onto the coach. “This worked for me” is not evidence that it is right for the participant.

When strong emotion appears, slow the interaction, support choice, and stay within role. If the participant needs trauma treatment, medical care, crisis intervention, or another specialized service, the coach should help with an appropriate referral rather than attempting to provide that service.',source_refs='[{"title":"SAMHSA Trauma-Informed Approaches and Programs","url":"https://www.samhsa.gov/mental-health/trauma-violence/trauma-informed-approaches-programs"},{"title":"2025 ICF Core Competencies","url":"https://coachingfederation.org/credentialing/coaching-competencies/icf-core-competencies/"},{"title":"ICF Code of Ethics (effective April 1, 2025)","url":"https://coachingfederation.org/credentialing/coaching-ethics/icf-code-of-ethics/"}]'::jsonb,practice_requirements='["Rewrite five directive or potentially retraumatizing coaching statements into language that increases choice, transparency, and collaboration.","Complete a cultural-humility reflection identifying assumptions a coach might make about family, recovery, work, housing, caregiving, faith, or help-seeking."]'::jsonb,review_status='internal_review',updated_at=now()
          where module_key='trauma_cultural_responsiveness' and course_id=(select id from public.professional_courses where course_key='coaching_foundations');
update public.professional_course_modules set content_md='# Coaching Communication Skills

Effective coaching communication is purposeful listening followed by questions and reflections that help the participant think more clearly. The 2025 ICF Core Competencies emphasize active listening, awareness, partnership, and growth. SAMHSA''s motivational guidance also supports communication that respects autonomy and reduces confrontation. Lellee uses these ideas as educational references; completing this course does not represent certification in Motivational Interviewing or an ICF credential.

Begin by listening for the participant''s words, priorities, values, uncertainty, strengths, and context. Reflect or summarize what you believe you heard and give the participant a chance to correct you. An accurate reflection is usually more useful than quickly giving advice.

Use open questions to expand thinking: “What matters most about this?” “What would make the next step realistic?” “What have you already tried?” Closed questions are useful for facts, but a conversation made entirely of yes/no questions can feel like an interview or compliance check.

Affirmations should identify real effort, strengths, values, or choices rather than offering empty praise. Summaries help connect themes and create transitions. Silence can be productive; do not rush to fill every pause.

Avoid the “righting reflex”—the urge to fix, persuade, lecture, or argue someone into change. When a participant is ambivalent, explore both sides without treating resistance as defiance. Ask permission before offering information or suggestions. After sharing information, return the conversation to the participant: what do they make of it, and what—if anything—do they want to do?

Emotion does not automatically turn coaching into therapy. A coach can acknowledge sadness, frustration, fear, anger, or uncertainty without analyzing its origin. The boundary changes when the participant needs diagnosis, treatment, trauma processing, or crisis intervention. At that point, support an appropriate handoff while remaining respectful and present.',source_refs='[{"title":"2025 ICF Core Competencies","url":"https://coachingfederation.org/credentialing/coaching-competencies/icf-core-competencies/"},{"title":"ICF Criteria for Assessing PCC Credential","url":"https://coachingfederation.org/credentialing/performance-evaluations/criteria-for-assessing-pcc/"},{"title":"SAMHSA TIP 35: Enhancing Motivation for Change","url":"https://www.samhsa.gov/resource/ebp/tip-35-enhancing-motivation-change-substance-use-disorder-treatment"}]'::jsonb,practice_requirements='["Convert ten advice-heavy statements into open questions, reflections, summaries, or permission-based information sharing.","Practice a five-minute coaching exchange using open questions, affirmations, reflections, summaries, and a participant-chosen next step."]'::jsonb,review_status='internal_review',updated_at=now()
          where module_key='communication_skills' and course_id=(select id from public.professional_courses where course_key='coaching_foundations');
update public.professional_course_modules set content_md='# Goals, Action Planning & Accountability

Goals in coaching belong to the participant. The coach can help make a goal clearer, smaller, more observable, and more realistic, but should not substitute the coach''s priorities for the participant''s. The ICF competencies emphasize partnering with clients to translate insight into action while supporting autonomy and accountability.

Start by clarifying the desired outcome and why it matters. A useful goal is specific enough to guide action but flexible enough to survive real life. Some participants benefit from SMART-style structure; others need a smaller “next doable step” before a detailed plan is useful. The method serves the person, not the other way around.

Break complex goals into actions that can be attempted between contacts. Identify what will happen, when it can happen, what resources are needed, what might get in the way, and what backup option exists. A strong plan includes the participant''s confidence level. If confidence is very low, the step is probably too large or not truly owned by the participant.

Accountability is a review process, not punishment. At the next contact, ask what happened and what was learned. A missed action is information. Explore barriers such as transportation, childcare, fear, competing priorities, fatigue, money, unclear instructions, or a goal that no longer fits. Avoid shame, threats, or manipulating access to essential support.

Celebrate progress without making the participant dependent on praise. Help them identify what they did that contributed to the result. When a plan succeeds, consolidate the learning. When it fails, adjust the plan. When the goal changes, document the new agreement rather than treating the change as noncompliance.

A coach can offer structure—checklists, reminders, calendars, step breakdowns, and progress reviews—while maintaining participant ownership. The goal is not to make someone follow the coach''s plan; it is to strengthen the participant''s ability to make and carry out their own informed decisions.',source_refs='[{"title":"2025 ICF Core Competencies","url":"https://coachingfederation.org/credentialing/coaching-competencies/icf-core-competencies/"},{"title":"ICF Code of Ethics (effective April 1, 2025)","url":"https://coachingfederation.org/credentialing/coaching-ethics/icf-code-of-ethics/"}]'::jsonb,practice_requirements='["Take three broad goals and create participant-led action plans with a next step, timing, barrier plan, confidence check, and follow-up question.","Rewrite punitive accountability language into neutral review language that treats missed actions as information."]'::jsonb,review_status='internal_review',updated_at=now()
          where module_key='goals_accountability' and course_id=(select id from public.professional_courses where course_key='coaching_foundations');
update public.professional_course_modules set content_md='# Documentation & Shared Progress

Good coaching documentation is useful, limited, accurate, and respectful. It supports continuity and accountability without turning a coaching note into a clinical record or a narrative about everything the participant disclosed.

Separate facts from interpretation. Record what the participant said, the goal discussed, agreed actions, resources provided, sharing decisions, and relevant follow-up. Avoid diagnostic labels, speculation about motives, unsupported conclusions, or language that would be inappropriate if the participant read the note. “Participant reported sleeping three hours” is different from making a clinical conclusion about what that means.

Document the coaching purpose, not curiosity. Sensitive details should only be recorded when they are necessary to the service or safety process. HHS and FTC guidance underscore that consumer health information may remain sensitive even when HIPAA does not govern a particular app or relationship. Lellee therefore treats recovery, health, caregiving, reentry, grief, and related information as data that should be minimized and protected.

Private journal information stays private unless the participant intentionally shares it through an approved mechanism. A coach should not copy private journal entries into coaching notes merely because access becomes technically possible. Shared progress should identify the source and the participant''s sharing choice.

Use neutral language for missed appointments, disagreement, recurrence, setbacks, or incomplete goals. Avoid labels such as “noncompliant,” “manipulative,” or “lazy” when an objective description is possible. If an incident or safety concern occurs, document the observable facts, what the participant reported, what action was taken, which policy or referral route was used, and any follow-up that remains.

Never alter records to conceal an error. If a correction is needed, follow the approved correction process so the change is transparent. Do not move coaching records into personal notes, text-message screenshots, or unapproved storage simply because it is convenient.',source_refs='[{"title":"ICF Code of Ethics (effective April 1, 2025)","url":"https://coachingfederation.org/credentialing/coaching-ethics/icf-code-of-ethics/"},{"title":"HHS Consumer Health App Privacy Guidance","url":"https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/cell-phone-hipaa/index.html"},{"title":"FTC Health Breach Notification Rule","url":"https://www.ftc.gov/legal-library/browse/rules/health-breach-notification-rule"}]'::jsonb,practice_requirements='["Rewrite eight judgmental or diagnostic note examples into objective coaching documentation.","Create a sample coaching note containing only purpose-relevant information, participant-selected goals, actions, referrals, and sharing decisions."]'::jsonb,review_status='internal_review',updated_at=now()
          where module_key='documentation_shared_progress' and course_id=(select id from public.professional_courses where course_key='coaching_foundations');
update public.professional_course_modules set content_md='# Risk Recognition, Referral & Escalation

Lellee coaching is not an emergency service and does not replace a clinical safety assessment, medical evaluation, emergency response, detoxification, or crisis treatment. Coaches still need to recognize when ordinary coaching must stop and a safety pathway must begin.

SAMHSA describes 988 as a behavioral-health crisis resource for emotional distress, suicidal crisis, and substance-use crisis support. 911 is for situations requiring immediate physical intervention, including medical emergencies or imminent threats to life or safety. When a participant appears to be in immediate physical danger or needs urgent medical intervention, use emergency services according to Lellee policy. When a participant is in behavioral-health crisis without immediate physical danger, support connection to 988 or another approved crisis resource.

A coach does not need to diagnose a crisis to take a concerning statement seriously. Pause goal work, stay focused on immediate safety, ask only the clear nonjudgmental questions needed to choose the correct route, and follow Lellee''s safety protocol. Do not debate, challenge, shame, or make the participant prove how serious the situation is.

Substance-use situations also require boundary awareness. Suspected overdose, severe withdrawal, loss of consciousness, breathing difficulty, or another medical emergency is not a coaching problem. Seek emergency help. Coaching may resume only after immediate safety and medical needs are addressed.

Other disclosures—abuse, violence, exploitation, threats to others, child or dependent-adult safety, or serious medical concerns—may trigger organizational procedures or legal duties depending on role and jurisdiction. Do not improvise legal conclusions. Follow the applicable Lellee policy, supervision route, and law. Do not promise absolute secrecy when a safety or reporting obligation may apply.

After an escalation, document facts and actions rather than clinical conclusions: what was reported or observed, what resource was offered, whether emergency services were contacted, who was notified under policy, and what follow-up is appropriate. A safety handoff should be respectful and as collaborative as the circumstances allow.',source_refs='[{"title":"SAMHSA 988 Frequently Asked Questions","url":"https://www.samhsa.gov/mental-health/988/faqs"},{"title":"SAMHSA Crisis Help","url":"https://www.samhsa.gov/find-support/in-crisis"},{"title":"ICF Code of Ethics (effective April 1, 2025)","url":"https://coachingfederation.org/credentialing/coaching-ethics/icf-code-of-ethics/"}]'::jsonb,practice_requirements='["Classify twelve scenarios as continue coaching, pause and refer, connect to 988, or contact 911/emergency services, and explain the boundary.","Write a factual safety note that records what was reported, the action taken, and the handoff without diagnosing the participant."]'::jsonb,review_status='internal_review',updated_at=now()
          where module_key='risk_referral_escalation' and course_id=(select id from public.professional_courses where course_key='coaching_foundations');
update public.professional_course_modules set content_md='# Foundations Applied Capstone

This capstone is reviewed by a human and cannot be passed by an automated quiz alone.

## Scenario

You are coaching Jordan, an adult participant using Lellee for recovery and employment goals. Jordan has recently lost a job, received a notice that threatens housing stability, and has stopped answering messages from supportive family members. During the session Jordan says they are feeling unsafe and hopeless and have been drinking more this week. They ask you to tell them whether they have depression, whether the housing notice is legal, and whether they should stop taking a prescribed medication because it makes them tired. They also ask you to send their private journal entries to a family member so the family will understand what is happening.

## Required response

Prepare a structured coaching response that demonstrates role clarity, immediate safety routing, privacy and consent, trauma-informed communication, participant-centered goal work, and objective documentation. Identify what you can address as a coach, what requires referral, what information you would and would not share, how you would respond to the safety concern, and how you would document the interaction.

The reviewer evaluates boundary recognition, safety judgment, communication quality, privacy protection, participant autonomy, referral choices, documentation quality, and whether the response avoids diagnosis, legal advice, medication advice, and unauthorized disclosure. An answer that misses a serious safety issue or provides clinical, legal, or medication directives cannot pass.',source_refs='[{"title":"ICF Code of Ethics (effective April 1, 2025)","url":"https://coachingfederation.org/credentialing/coaching-ethics/icf-code-of-ethics/"},{"title":"2025 ICF Core Competencies","url":"https://coachingfederation.org/credentialing/coaching-competencies/icf-core-competencies/"},{"title":"SAMHSA Trauma-Informed Approaches and Programs","url":"https://www.samhsa.gov/mental-health/trauma-violence/trauma-informed-approaches-programs"},{"title":"SAMHSA 988 Frequently Asked Questions","url":"https://www.samhsa.gov/mental-health/988/faqs"},{"title":"SAMHSA Crisis Help","url":"https://www.samhsa.gov/find-support/in-crisis"},{"title":"HHS Consumer Health App Privacy Guidance","url":"https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/cell-phone-hipaa/index.html"},{"title":"FTC Health Breach Notification Rule","url":"https://www.ftc.gov/legal-library/browse/rules/health-breach-notification-rule"}]'::jsonb,practice_requirements='["Submit a written response addressing scope, safety, privacy, communication, goals, referral, and documentation.","Complete a self-audit identifying every point where the scenario could pull the coach outside role."]'::jsonb,review_status='internal_review',updated_at=now()
          where module_key='foundations_capstone' and course_id=(select id from public.professional_courses where course_key='coaching_foundations');
update public.professional_courses set curriculum_review_status='internal_review',status='draft',checkout_enabled=false,updated_at=now() where course_key='coaching_foundations';
commit;